export const types = {
  AUTH_START: "AUTH_START",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILD: "AUTH_FAILD",
  
  SING_OUT: "SING_OUT",
  
  
  GET_USER_START: "GET_USER_START",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",

  SET_USER_START: "SET_USER_START",
  SET_USER_SUCCESS: "SET_USER_SUCCESS",
  SET_USER_FAILED: "SET_USER_FAILED",
  
};
